export const REGISTERADMIN = 'REGISTER'
export const REGISTERADMIN_SUCCSS = 'REGISTER_SUCCSS'
export const REGISTERADMIN_FAIL = 'REGISTER_FAIL'

export const LOGINADMIN = 'LOGIN'
export const LOGINADMIN_SUCCSS = 'LOGIN_SUCCSS'
export const LOGINADMIN_FAIL = 'LOGIN_FAIL'